// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMBA_7_2_.Data;

#nullable disable

namespace WMBA_7_2_.Data.WMBAMigrations
{
    [DbContext(typeof(WMBAContext))]
    [Migration("20240124004503_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");
#pragma warning restore 612, 618
        }
    }
}
